# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-20 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtag',
            old_name='data_modified',
            new_name='date_modified',
        ),
    ]
