# Generated by Django 2.0.1 on 2018-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_id', models.PositiveIntegerField(default=1, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=225)),
                ('last_name', models.CharField(blank=True, max_length=225)),
                ('notes', models.TextField(blank=True)),
                ('loc_lat', models.FloatField()),
                ('loc_lon', models.FloatField()),
                ('severity', models.CharField(choices=[('SR', 'Severe'), ('MO', 'Moderate'), ('MD', 'Mild')], default='SR', max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
