# Generated by Django 2.0.1 on 2018-01-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtag',
            name='id',
        ),
        migrations.AlterField(
            model_name='dtag',
            name='barcode_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
