# Generated by Django 2.0.1 on 2018-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtag',
            name='loc_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dtag',
            name='loc_lon',
            field=models.FloatField(default=0),
        ),
    ]
