# Generated by Django 2.0.1 on 2018-01-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0003_dtag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtag',
            name='image',
            field=models.ImageField(default='static/img/default.jpeg', upload_to='static/img/{{ barcode_id }}/'),
        ),
    ]
