# Generated by Django 2.0.1 on 2018-01-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0004_auto_20180121_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtag',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
