# Generated by Django 2.0.1 on 2018-01-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0008_remove_dtag_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtag',
            name='barcode_id',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
