# Generated by Django 2.0.1 on 2018-01-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0009_dtag_barcode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtag',
            name='barcode_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
