# Generated by Django 2.0.1 on 2018-01-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0009_dtag_barcode_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtag',
            name='image',
        ),
    ]
