# Generated by Django 2.0.1 on 2018-01-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0010_auto_20180121_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtag',
            name='image',
        ),
        migrations.AlterField(
            model_name='dtag',
            name='barcode_id',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
