# Generated by Django 2.0.1 on 2018-01-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dtags', '0010_remove_dtag_image'),
        ('dtags', '0011_auto_20180121_0804'),
    ]

    operations = [
    ]
